# Generated by Django 4.2.1 on 2023-06-29 16:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('seguro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('imagen_activos', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Portada')),
                ('imagen_activos2', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Contenido')),
                ('url_video', models.URLField(blank=True, default=None, null=True)),
                ('nombre', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('definicion', models.TextField(blank=True, default=None, null=True)),
                ('beneficio', models.TextField(blank=True, default=None, null=True)),
                ('elegibilidad', models.TextField(blank=True, default=None, null=True)),
                ('exepciones', models.TextField(blank=True, default=None, null=True)),
                ('adicionales', models.TextField(blank=True, default=None, null=True)),
                ('caracteristicas', models.TextField(blank=True, default=None, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('seguro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguro.seguro')),
            ],
            options={
                'verbose_name': 'Modalidad',
            },
        ),
    ]
