# Generated by Django 4.2.1 on 2023-06-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modalidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modalidad',
            options={'verbose_name': 'Modalidad', 'verbose_name_plural': 'Modalidades'},
        ),
    ]
