# Generated by Django 4.2.1 on 2023-06-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='empresa',
            new_name='nombre',
        ),
    ]
