# Generated by Django 4.2.1 on 2023-06-29 17:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seguro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('producto', models.CharField(max_length=200, verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.RenameField(
            model_name='seguro',
            old_name='seguro',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='seguro',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='seguro',
            name='tipo',
        ),
        migrations.CreateModel(
            name='TipoSeguro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo', models.CharField(max_length=200, verbose_name='Tipo de Seguro')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguro.producto')),
            ],
            options={
                'verbose_name': 'Tipo de Seguro',
                'verbose_name_plural': 'Tipos de Seguros',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='seguro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguro.seguro'),
        ),
    ]
